using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using YoutubeExplode;
using YoutubeExplode.Videos.ClosedCaptions;

namespace YouTubeSubs;

internal sealed record SubtitleTrack(string Language, string Code, bool Generated, ClosedCaptionTrackInfo Source);
internal sealed record VideoInfo(string VideoId, string Title, List<SubtitleTrack> Tracks, string OriginalCode)
{
    public List<(string Label, string Code)> LanguageChoices()
    {
        var result = new List<(string Label, string Code)>();
        foreach (var group in Tracks.GroupBy(t => t.Code, StringComparer.OrdinalIgnoreCase))
        {
            var first = group.First();
            var kinds = new List<string>();
            if (group.Any(t => !t.Generated)) kinds.Add("manual");
            if (group.Any(t => t.Generated)) kinds.Add("auto");
            result.Add(($"{first.Language} ({first.Code}) — {string.Join(" + ", kinds)}", first.Code));
        }
        return result;
    }
}

internal sealed class YoutubeService
{
    private readonly YoutubeClient _youtube = new();
    private static readonly Regex VideoIdRegex = new("^[A-Za-z0-9_-]{11}$", RegexOptions.Compiled);
    private static readonly Regex AnywhereRegex = new("(?<![A-Za-z0-9_-])([A-Za-z0-9_-]{11})(?![A-Za-z0-9_-])", RegexOptions.Compiled);

    public static string ExtractVideoId(string input)
    {
        var value = input.Trim();
        if (VideoIdRegex.IsMatch(value))
            return value;

        foreach (var pattern in new[]
        {
            @"(?:[?&]v=)([A-Za-z0-9_-]{11})",
            @"(?:youtu\.be/)([A-Za-z0-9_-]{11})",
            @"(?:youtube(?:-nocookie)?\.com/(?:shorts|embed|live)/)([A-Za-z0-9_-]{11})",
        })
        {
            var match = Regex.Match(value, pattern, RegexOptions.IgnoreCase);
            if (match.Success)
                return match.Groups[1].Value;
        }

        var candidates = AnywhereRegex.Matches(value).Select(m => m.Groups[1].Value).Distinct().ToList();
        if (candidates.Count == 1)
            return candidates[0];

        if (Uri.TryCreate(value, UriKind.Absolute, out var uri))
        {
            var host = uri.Host.ToLowerInvariant();
            if (host is "youtu.be" or "www.youtu.be")
            {
                var candidate = uri.AbsolutePath.Trim('/').Split('/')[0];
                if (VideoIdRegex.IsMatch(candidate)) return candidate;
            }
            else if (host.EndsWith("youtube.com", StringComparison.OrdinalIgnoreCase))
            {
                if (uri.AbsolutePath == "/watch")
                {
                    var query = System.Web.HttpUtility.ParseQueryString(uri.Query);
                    var candidate = query["v"] ?? string.Empty;
                    if (VideoIdRegex.IsMatch(candidate)) return candidate;
                }
                else
                {
                    var parts = uri.AbsolutePath.Split('/', StringSplitOptions.RemoveEmptyEntries);
                    if (parts.Length >= 2 && parts[0] is "shorts" or "embed" or "live" && VideoIdRegex.IsMatch(parts[1]))
                        return parts[1];
                }
            }
        }

        throw new ArgumentException("Invalid YouTube URL or video ID.");
    }

    public static string CanonicalUrl(string videoId) => $"https://www.youtube.com/watch?v={videoId}";

    public static string CleanFilename(string name)
    {
        var invalid = new string(Path.GetInvalidFileNameChars());
        var cleaned = Regex.Replace(name, $"[{Regex.Escape(invalid)}]", "_").Trim().TrimEnd('.', ' ');
        return string.IsNullOrWhiteSpace(cleaned) ? "youtube_subtitles" : cleaned[..Math.Min(180, cleaned.Length)];
    }

    public async Task<VideoInfo> AnalyzeAsync(string input, Action<string>? phase, CancellationToken cancellationToken)
    {
        var videoId = ExtractVideoId(input);
        phase?.Invoke("metadata");
        cancellationToken.ThrowIfCancellationRequested();
        var video = await _youtube.Videos.GetAsync(videoId, cancellationToken);

        phase?.Invoke("transcripts");
        var manifest = await _youtube.Videos.ClosedCaptions.GetManifestAsync(videoId, cancellationToken);
        cancellationToken.ThrowIfCancellationRequested();
        if (manifest.Tracks.Count == 0)
            throw new InvalidOperationException("This video has no available subtitles.");

        var tracks = manifest.Tracks
            .Select(t => new SubtitleTrack(t.Language.Name, t.Language.Code, t.IsAutoGenerated, t))
            .ToList();
        var original = tracks.FirstOrDefault(t => t.Generated)?.Code ?? tracks[0].Code;
        return new VideoInfo(videoId, video.Title, tracks, original);
    }

    public async Task<string> DownloadAndFormatAsync(VideoInfo info, string format, string? languageCode, Action<string>? phase, CancellationToken cancellationToken)
    {
        var code = languageCode ?? info.OriginalCode;
        var matches = info.Tracks.Where(t => string.Equals(t.Code, code, StringComparison.OrdinalIgnoreCase)).ToList();
        if (matches.Count == 0)
            throw new InvalidOperationException($"No subtitle track is available for language '{code}'.");

        var selected = matches.FirstOrDefault(t => !t.Generated) ?? matches[0];
        phase?.Invoke("download");
        var track = await _youtube.Videos.ClosedCaptions.GetAsync(selected.Source, cancellationToken);
        cancellationToken.ThrowIfCancellationRequested();
        phase?.Invoke("format");
        return Format(track, format);
    }

    private static string Format(ClosedCaptionTrack track, string format)
    {
        return format switch
        {
            "txt" => string.Join(Environment.NewLine, track.Captions.Select(c => c.Text)),
            "srt" => FormatSrt(track),
            "vtt" => FormatVtt(track),
            "sub" => FormatSub(track),
            _ => throw new ArgumentException($"Unsupported format '{format}'."),
        };
    }

    private static string FormatSrt(ClosedCaptionTrack track)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < track.Captions.Count; i++)
        {
            var c = track.Captions[i];
            sb.AppendLine((i + 1).ToString(CultureInfo.InvariantCulture));
            sb.Append(Stamp(c.Offset, false, true)).Append(" --> ").AppendLine(Stamp(c.Offset + c.Duration, false, true));
            sb.AppendLine(c.Text).AppendLine();
        }
        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string FormatVtt(ClosedCaptionTrack track)
    {
        var sb = new StringBuilder("WEBVTT").AppendLine().AppendLine();
        foreach (var c in track.Captions)
        {
            sb.Append(Stamp(c.Offset, true, false)).Append(" --> ").AppendLine(Stamp(c.Offset + c.Duration, true, false));
            sb.AppendLine(c.Text).AppendLine();
        }
        return sb.ToString();
    }

    private static string FormatSub(ClosedCaptionTrack track)
    {
        var sb = new StringBuilder();
        foreach (var c in track.Captions)
        {
            sb.Append(Stamp(c.Offset, false, false)).Append(',').AppendLine(Stamp(c.Offset + c.Duration, false, false));
            sb.AppendLine(c.Text.Replace(Environment.NewLine, "[br]")).AppendLine();
        }
        return sb.ToString();
    }

    private static string Stamp(TimeSpan time, bool vtt, bool srt)
    {
        var hours = (int)Math.Floor(time.TotalHours);
        var sep = vtt ? '.' : srt ? ',' : ':';
        return $"{hours:00}:{time.Minutes:00}:{time.Seconds:00}{sep}{time.Milliseconds:000}";
    }
}
